### PR TITLE
fix AST parsing with ':' in filenames

### PR DESCRIPTION
**Pull request by Spongman**
eg, on windows (C:\\...)

### CODE REVIEW

**Comment by Spongman** [comment]
fixes https://github.com/yasuyuky/autocomplete-clang/issues/139

**Comment by Spongman** [comment]
i'm pretty sure the `split ' '` is still broken if filenames have spaces...

**Comment by yasuyuky** [comment]
Looks Good. Thanks!

**Comment by AStupidBear** [comment]
@yasuyuky Can you tag a new release such that I can use this package on windows?

**Pull request merged**
