### PR TITLE
Added support for include paths, relative to the current file.

### PR DESCRIPTION
**Pull request by DimitriJanssens**
Added support for include paths, relative to the current file ie. ../header, and others.
This allows support for a more modular build system setup.

### CODE REVIEW

**Comment by DimitriJanssens** [comment]
@yasuyuky Please review my merge request :)

**Comment by yasuyuky** [comment]
The `includePath` feature is intended to be used for including some kind of *standard* paths of your system. 
You can use clang-complete for including relative path.
I expect it's enough for your project.

**Comment by DimitriJanssens** [comment]
Let me explain a bit more.
My directory structure is setup like the example below.

.clang_complete works only relative to the folder it is in ...
This means, that **for every module/library I write**, I would have to change the clang_complete file to add my header folder ... *hmmm, there must be a better way*

The clang args builder inside autocomplete on the other hand, knows what file I am editing. By adding the feature `includeRelativePath`, I, and I believe a lot of other users as well, can simply add their header folder, relative to the current src file (../header) to the clang arguments.

The current sourcefiles's folder is already automatically added by the clang args builder as an include path, relative to the current directory. I just expanded this feature.

For readability, I renamed `includePath` into `includeAbsolutePath`.

I thought this feature could be usefull for other programmers as well, therefore I created the pull request.

Feel free to rejudge and leave a comment.
No harm taken if the feature is considered very specific towards my project setup.

```
-- globalincludes == symbolic links towards interfaces of modules
-- applications
  |-- app1
      |-- header  /* .h files */
      |-- src         /*.c files */
  |-- app2
      |-- header  /* .h files */
      |-- src         /*.c files */
-- modules
  |-- module1
      |-- export   /* .h files = interfaces towards module*/
      |-- header  /* .h files */
      |-- src         /*.c files */
  |-- module2
      |-- export   /* .h files = interfaces towards module*/
      |-- header  /* .h files */
      |-- src         /*.c files */
```

**Comment by yasuyuky** [comment]
>  I would have to change the clang_complete file to add my header folder

It doesn't make sense to me.

To place *same* `.clang_complete` files per project solves your problem.

like this
```
-- applications
  |-- app1
      |-- .clang_complete /* -I./header */
      |-- header  /* .h files */
      |-- src         /*.c files */
  |-- app2
      |-- .clang_complete /* -I./header */
      |-- header  /* .h files */
      |-- src         /*.c files */
```

So what you need to do for initializing a directory are following steps.

```bash
cd /path/to/your/app/dir
mkdir header
mkdir src
echo "-I./header" >> .clang_complete
```

**Comment by DimitriJanssens** [comment]
Hmm, I did not think about that one ...
That is indeed a simple solution for other users!

Personally, I rather prefer my IDE to be a tool, and my code repositories should not contain any artifacts of the IDE, or other developer helping tools I am using. That's the main reason for starting this change.

You can close the pull request if you want to. :)

PS: expect some more pull requests from me in the future! ;)

**Comment by yasuyuky** [comment]
OK, thanks again for your pull request ;)

**Pull request closed without merging**
