### PR TITLE
Add check for autocomplete-plus minimumWordLength

### PR DESCRIPTION
**Pull request by mr-frog**
I've changed some of the code in ClangProvider.getSuggestions, so that the Minimum Word Length setting from autocomplete-plus is taken into account. (i.e. no suggestions are shown until the minimum word length is reached.)

This should fix issue #77, and is related to some of the stuff being discussed at the end of issue #66.

(also, apologies if I've done this wrong, this is my first pull request on GitHub!)

### CODE REVIEW

**Comment by vladimir-didenko** [comment]
Is it possible to implement feature such way that minimum length will not be used for structure fields (after '.' and '->')? I believe that many users expect such behavior.

**Comment by mr-frog** [comment]
Thank you for your suggestion, @vladimir-didenko.

For now, I've added in checks so that if the last character is `.` or `>`, the `minimumWordLength` will be ignored. This is a bit of a hack though, since whenever `>` is typed in (e.g. `x > 5`) all of the suggestions will pop up as before.

**Comment by mr-frog** [comment]
OK, I've set up a proper regex so that autocomplete only goes off when it follows a member access operator. (i.e. `.` or `->`)

At the same time, I cleaned up some of the regexs already in use. For some reason, the symbol `-` was being included as part of the identifier when generating a prefix: I assume that the `prefixAtPosition` function had just been copied [off the wiki](https://github.com/atom/autocomplete-plus/wiki/Provider-API#generating-a-new-prefix).

**Comment by yasuyuky** [comment]
Thank you for the great contribution! :laughing:

**Pull request merged**
