### PR TITLE
Add goto declaration of symbols

### PR DESCRIPTION
**Pull request by dwampler35**
This feature looks up the declaration of a symbol under cursor and opens that file in the workspace at the appropriate position in the file.

### CODE REVIEW

**Comment by raiuli** [comment]
i want to have this feature.. can i add it in my current installation

**Comment by dwampler35** [comment]
Sure just copy to ~/.atom/packages/autocomplete-clang

**Comment by ivankravets** [comment]
@yasuyuky do you have any objections to this PR?

**Comment by yasuyuky** [comment]
Hello.
Thanks for your PR and sorry for late reply.
I think this is great feature.
I have tried this feature and have some questions.

1. This is more useful that goto declaration to variable. 
    Currently this PR's feature may only support function or method.
    (And source file to header file jump)
    Supporting "jump to variable" in same source file is more useful.
    I already have some codes to support the feature in my local environment.
    So after merge of this PR, I tried to commit on this.
    What do you think about it?
 
2. I think " Ctrl+i" keyboard shortcut may be too common for this feature.
    Is this used in some other IDEs? (Xcode,VS,Eclipse,JetBrains,Vim,Emacs....)

**Comment by dwampler35** [comment]
1).  Goto in source file is something that I need sometimes.  It's great
that you already have something for this.  Switch header/source and a few
other functions also would be nice.  It's possible to implement these with
Clang.

2). I wasn't sure about the key binding either.  IDEs seem to be all over
the map on this.  Qtcreator uses ctrl+F2, eclipse uses just F3.  Vim uses
ctrl+ ].  Those are the only ones I use regularly.

**Comment by ivankravets** [comment]
Guys, I've just found https://atom.io/packages/hyperclick . FB uses it for "Go To". 

Dou have idea how to integrate that package to `autocomplete-clang`?

**Comment by yasuyuky** [comment]
@ivankravets 
It looks nice.
But the package using clang already seems to exist, does not?

**Comment by yasuyuky** [comment]
Now, this branch has been merged.
After some fix, this feature will be released.
Thanks for your contributions. 👍

**Comment by ivankravets** [comment]
@yasuyuky FB shares only this package. Other packages are not published to the Atom registry. They keep these within an own package. See

* https://github.com/facebook/nuclide/tree/master/pkg/nuclide-clang-atom
* https://github.com/facebook/nuclide/tree/master/pkg/nuclide-clang

**Pull request merged**
